config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  resources :companies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_rich_text :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, except: [:index, :create, :new]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def show
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path, notice: "Saved"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @company.update(company_params)
      redirect_to companies_path, notice: "Changes Saved"
    else
      render :edit
    end
  end

  private
    def company_params
      params.require(:company).permit(
        :name,
        :legal_name,
        :description,
        :zip_code,
        :phone,
        :email,
        :owner_id,
        services: []
      )
    end

    def set_company
      @company = Company.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/companies/_form.html.erb
<div class="py-5">
  <%= form_for @company do |f| %>

    <div class="row my-lg-3">
      <div class="col-lg-3">
        <label><strong>Name</strong><br><small class="text-muted">The public DBA, or Common name of the organization</small></label>
      </div>
      <div class="col-lg offset-lg-1">
        <div class="form-group">
          <%= f.text_field :name, class: "form-control", placeholder: "Company Name", required: true %>
        </div>
      </div>
    </div>


    <div class="row my-lg-3">
      <div class="col-lg-3">
        <label><strong>Zip Code</strong><br><small class="text-muted">5 Digit US postal code</small></label>
      </div>
      <div class="col-lg offset-lg-1">
        <div class="form-group">
          <%= f.text_field :zip_code, class: "form-control", placeholder: "93003", required: true %>
        </div>
      </div>
    </div>

    <div class="row my-lg-3">
      <div class="col-lg-3">
        <label><strong>Description</strong><br><small class="text-muted">Rich text marketing description</small></label>
      </div>
      <div class="col-lg-8 offset-lg-1">
        <div class="form-group">
          <%= f.rich_text_area :description %>
        </div>
      </div>
    </div>


    <div class="row my-lg-3">
      <div class="col-lg-3">
        <label><strong>Phone</strong><br><small class="text-muted">Shown in marketing</small></label>
      </div>
      <div class="col-lg offset-lg-1">
        <div class="form-group">
          <%= f.text_field :phone, class: "form-control", placeholder: "555-555-5555"%>
        </div>
      </div>
    </div>

    <div class="row my-lg-3">
      <div class="col-lg-3">
        <label><strong>Email</strong><br><small class="text-muted">Shown in marketing</small></label>
      </div>
      <div class="col-lg offset-lg-1">
        <div class="form-group">
          <%= f.text_field :email, class: "form-control", placeholder: "hello@company.com"%>
        </div>
      </div>
    </div>

    <div class="row my-lg-3">
      <div class="col-lg-3">
        <label><strong>Services</strong><br><small class="text-muted">List the services offered by this company</small></label>
      </div>
      <div class="col-lg offset-lg-1">
          <div data-controller="services" class="form-group">
            <%= f.select :services, options_for_select(["Interior Painting", "Commercial Painting", "Exterior Painting"], @company.services), {include_blank: true, required: false}, multiple: true, "data-target": "services.select2", class: "form-control" %>
          </div>
      </div>
    </div>

    <div class="row my-lg-3">
      <div class="col">
        <div class="form-group">
          <%= f.submit class: "btn btn-success"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/companies/edit.html.erb
<div class="container py-5">
  <h3>Edit Company</h3>
  <%= link_to "< Company", company_path(@company) %>
  <%= render "form" %>
</div>

app/views/companies/index.html.erb
<div class="container py-5">
  <h3>Companies</h3>
  <%= link_to "+ Create a Company", new_company_path %><br>
  <% if @companies.empty? %>
  <p>No Companies Found</p>
  <% else %>
    <ul class="list-group my-5">
      <% @companies.each do |company| %>
        <a href="<%= company_path(company) %>" class="list-group-item list-group-item-action">
          <%= company.name %>
        </a>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/companies/new.html.erb
<div class="container py-5">
  <h3>New Company</h3>
  <%= link_to "< Companies", companies_path %>
  <%= render "form" %>
</div>

app/views/companies/show.html.erb
<div class="container py-5">
  <h3>Company</h3>
  <div class="row">
    <div class="col">
      <%= link_to "< Companies", companies_path %>
    </div>
    <div class="col text-right">
      <%= link_to "Edit", edit_company_path %>
    </div>
  </div>
  <div class="bg-success">
    <div class="container p-5 text-white">
      <h1><%= @company.name %></h1>
      <h3><mark>City, State</mark></h3>
      <pre><mark>☝️ This is what needs to be udpated. Examples: Atlanta, GA or Nashvile, TN</mark></pre>
    </div>
  </div>

  <div class="row bg-light">
    <div class="col-12 col-lg-8 p-lg-5 pt-4">
      <%= @company.description %>
    </div>
    <div class="col-12 col-lg-4 pt-lg-5">
      <h4>Services</h4>
      <% @company.services.reject(&:blank?).each do |service| %>
        <p><%= service %></p>
      <% end %>
      <h4>Contact</h4>
        <div class="form-group" data-controller="clipboard">
          <p><%= @company.phone %><br>
          <input type="hidden" value="<%= @company.phone %>" data-target="clipboard.source"></input>
          <a data-action="clipboard#copy" class="clipboard-button pointer text-decoration-none text-dark"> copy</a>
          <a data-target="clipboard.notice" class="clipboard-button pointer d-none text-decoration-none text-dark" class="d-none"> copied</a> 
          </p>         
        </div>
    </div>
  </div>

  <div class="bg-success text-white text-center py-3">
    <p class="lead"><%= @company.phone %> — <%= @company.email %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'shared/notices' %>
    <%= yield %>
    <div class="fixed-bottom bg-light">
    <div class="container py-3">
      <%= link_to "Home", root_path, class: "mr-5"  %>
      <%= link_to "Companies", companies_path, class: "mr-5" %>
    </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container py-5">
  <div class="col-lg-8 offset-lg-2">
    <h1>Welcome 👋</h1>
    <p>Be sure you check out the REAMDE.md for specific tasks to be completed.</p>
    <p class="lead">Note: This codebase is <mark>not nearly fully representative of our platform</mark> however it's a good small sample of the kinds of technology and problems we are solving. </p>
    <ul class="my-5 list-group">
      <li class="list-group-item">
        <h3><strong>Challenge Steps</strong></h3>
        <p>Please refer to our <a href="https://www.notion.so/getmainstreet/Engineering-Wiki-92df623daaeb4022892d331feb20aadf" target="_blank">Engineering Wiki</a> for our best practices and recommended approaches.</p>
        <p>You can also feel free to look at <a href="https://github.com/main-street/code-challenge/pulls" target="_blank">past PR's</a> for how other developers have solved some of these challenges. Although keep in mind, you'll need to be able to explain your submission and talk through your choices.</p>
      </li>
      <li class="list-group-item">
        <h5><strong>☐ Add a way to delete companies</strong></h5>
        <p>For companies, there isn't currently a way to destroy them. There should be a confirmation of the action. Some kind of "Are you sure?" message.</p>
        <p><small>Assessing: Basic Rails Knowledge and established best practices.</small></p>
      </li>
      <li class="list-group-item">
        <h5><strong>☐ Add Custom Validation to company email</strong></h5>
        <p>(When Present) All email addresses for new companies should only be a @getmainstreet.com domain. A custom error should render when attempting to create or update a company when the email does not match this domain. This should only be when email is present. Blank emails can be ignored. Should validate on both front end and back end.</p>
        <p><small>Assessing: Basic Rails Knowledge and established best practices.</small></p>
      </li>
      <li class="list-group-item">
        <h5><strong>☐ Add City State To Companies from Zip Code</strong></h5>
        <p>For each company "Show" page there is a placeholder for the <strong>City, State</strong> for that company. You'll need to leverage the zip code to have that value render the actual <strong>City, State</strong>. For example: <strong> Nashville, TN</strong> You might want to take a look at the <a href="https://github.com/monterail/zip-codes">ZipCodes gem</a> that is already in this project.</p>
        <p>Every time the company's zip code is updated this city and state should be updated.</p>
        <p>The City and State should be added as attributes to the Company object.</p>
        <p><small>Assessing: Back end skills. Ability to implement more back-end heavy, basic business logic in the context of rails while leveraging established Gems / Libraries.</small></p>
      </li>
      <li class="list-group-item">
        <h5><strong>☐ Include a way to set a brand color</strong></h5>
        <p>Companies should be able to pick or enter a color and have that color render on the company show page. Ideally, this interface should feel responsive and interactive in some way.</p>
        <p><small>Assessing: Front end skills. Basic UX and UI Instinct. Ability to leverage CSS / HTML / JavaScript to build an engaging and reactive UI.</small></p>
      </li>
      <li class="list-group-item">
        <h5><strong>☐ Include test coverage for all your changes</strong></h5>
        <p>For all functionality extend or add tests from existing tests.</p>
        <p><small>Assessing: Ability to produce clean tests and documentation for code.</small></p>
      </li>
      <li class="list-group-item">
        <h5><strong>☐ Suggest a new task for this challenge</strong></h5>
        <p>Write up a proposed challenge to add to this repository for assesing developers. Do not solve the code challenge. Just write the task, and why this would make a good challenge to include for future developers.</p>
        <p><small>Assessing: Engineering instinct, writing, ability to document up a deliverable concisely.</small></p>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>" id="alert_message"  >
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message.html_safe %>
    </div>
  </div>
<% end %>